version: '3.4'

services:
  portal:
    container_name: "portal-web"
    image: etacom-portal
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: ${CERTIFICATE_CONTAINER_PATH}/${ASPNETCORE_KESTREL_CERTIFICATE_FILENAME}
      ConnectionStrings__DefaultConnection: "Server=db.internal.prod.com,1433;Database=Portal;User=sa;Password=_passPass1;MultipleActiveResultSets=true"
    build:
      context: ./Portal
    ports:
      - "59246:80"
      - "44317:443"
    volumes:
      - ${CERTIFICATE_PATH}:${CERTIFICATE_CONTAINER_PATH}
    depends_on:
      - db
    networks:
      mynetwork:
        aliases:
          - web1.internal.prod.com

  db:
    image: "mcr.microsoft.com/mssql/server"
#    image: microsoft/mssql-server-windows-express
    container_name: "portal-sqlserver"
    environment:
      SA_PASSWORD: "_passPass1"
      ACCEPT_EULA: "Y"
    ports:
      - "11433:1433"
    volumes:
      - ${SQL_SERVER_VOLUME_PATH}:${SQL_SERVER_CONTAINER_VOLUME_PATH}
    networks:
      mynetwork:
        aliases:
          - db.internal.prod.com

networks:
  mynetwork:
    driver: ${NETWORK_DRIVER}
